export enum envEnum {
    JWT_SECRET = 'JWT_SECRET',
    JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
    JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
    JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    DATABASE_URL = 'DATABASE_URL',
    RESEND_API_KEY = 'RESEND_API_KEY',
    EMAIL_FROM = 'EMAIL_FROM',
    APP_URL = 'APP_URL',
}