export const EMERGENCY_KEYWORDS = [
  'convulsion',
  'convulsions',
  'seizure',
  'seizures',
  'not breathing',
  'cannot breathe',
  "can't breathe",
  'stopped breathing',
  'excessive bleeding',
  'heavy bleeding',
  'bleeding heavily',
  'no movement',
  'not moving',
  'loss of consciousness',
  'lost consciousness',
  'unconscious',
  'passed out',
  'fainting repeatedly',
  'severe chest pain',
  'suicide',
  'want to die',
];
