export const VACCINATION_KEYWORDS = [
  'vaccine',
  'vaccination',
  'vaccinate',
  'vaccinated',
  'immunization',
  'immunisation',
  'immunize',
  'immunise',
  'bcg',
  'opv',
  'penta',
  'pcv',
  'rotavirus',
  'measles',
  'rubella',
  'yellow fever',
  'vitamin a',
  'hepatitis b',
  'aefi',
  'side effect',
  'side effects',
  'adverse reaction',
  'booster',
  'immunization schedule',
  'vaccination schedule',
  'due date for vaccine',
  'missed vaccine',
  'overdue vaccine',
];
